sudo: required
language: generic
services:
  - docker

before_install:
    - docker build -t rmcr714/react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true rmcr714/react-test npm test


after_success:
   - docker build -t rmcr714/multi-client ./client
   - docker build -t rmcr714/multi-nginx ./nginx
   - docker build -t rmcr714/multi-server ./server
   - docker build -t rmcr714/multi-worker ./worker

   #login to docker cli
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

   #push to dcoker hub
   - docker push rmcr714/multi-client
   - docker push rmcr714/multi-nginx
   - docker push rmcr714/multi-server
   - docker push rmcr714/multi-worker
