sudo: required
language: generic
services:
  - docker

before_install:
    - docker build -t rmcr714/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rmcr714/react-test npm test


after_success:
   - docker build -t rmcr714/multi-client ./client
   - docker build -t rmcr714/multi-nginx ./nginx
   - docker build -t rmcr714/multi-server ./server
   - docker build -t rmcr714/multi-worker ./worker

   #login to docker cli
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

   #push to dcoker hub
   - docker push rmcr714/multi-client
   - docker push rmcr714/multi-nginx
   - docker push rmcr714/multi-server
   - docker push rmcr714/multi-worker

deploy:
   provider: elasticbeanstalk
   region: "ap-south-1"
   app: "multi-docker"
   env: "Multidocker-env"
   bucket_name: "elasticbeanstalk-ap-south-1-159525289937"
   bucket_path: "docker-react"
   on:
    branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY
